SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
BOARD_REGION = 800
BOARD_ORIGIN_X = 40
BOARD_ORIGIN_Y = 40
SIDE_PANEL_GAP = 40
SIDE_PANEL_RIGHT_MARGIN = 40
SIDE_PANEL_LEFT = BOARD_ORIGIN_X + BOARD_REGION + SIDE_PANEL_GAP
SIDE_PANEL_TOP = 100
SIDE_PANEL_WIDTH = SCREEN_WIDTH - SIDE_PANEL_LEFT - SIDE_PANEL_RIGHT_MARGIN
SIDE_PANEL_PADDING = 20
LINE_WIDTH = 1
MOVE_LIMIT = 15
REVEAL_DURATION = 1300  # milliseconds

LABEL_PADDING = 6

MENU_BUTTON_WIDTH = 520
MENU_BUTTON_HEIGHT = 64
MENU_BUTTON_GAP = 24
MENU_BUTTON_LEFT = (SCREEN_WIDTH - MENU_BUTTON_WIDTH) // 2
MENU_BUTTON_STACK_HEIGHT = 2 * MENU_BUTTON_HEIGHT + MENU_BUTTON_GAP
MENU_FIRST_BUTTON_TOP = (SCREEN_HEIGHT - MENU_BUTTON_STACK_HEIGHT) // 2
MENU_TITLE_OFFSET = 80
MENU_TITLE_TOP = MENU_FIRST_BUTTON_TOP - MENU_TITLE_OFFSET
# Game Select stacks three buttons (M7.b added Settings); Subject stacks two.
MENU_THREE_BUTTON_STACK_HEIGHT = 3 * MENU_BUTTON_HEIGHT + 2 * MENU_BUTTON_GAP
MENU_THREE_FIRST_BUTTON_TOP = (SCREEN_HEIGHT - MENU_THREE_BUTTON_STACK_HEIGHT) // 2
MENU_THREE_TITLE_TOP = MENU_THREE_FIRST_BUTTON_TOP - MENU_TITLE_OFFSET

MENU_CHECKBOX_SIZE = 30
MENU_ROW_HEIGHT = 52
MENU_LIST_SIDE_PADDING = 8
MENU_TOPICS_TITLE_TOP = SCREEN_HEIGHT // 5
MENU_SCROLL_TOP = MENU_TOPICS_TITLE_TOP + MENU_TITLE_OFFSET
MENU_BOTTOM_MARGIN = 80
MENU_START_TOP = SCREEN_HEIGHT - MENU_BOTTOM_MARGIN - MENU_BUTTON_HEIGHT
MENU_LIST_START_GAP = 24
MENU_VISIBLE_ROWS = (MENU_START_TOP - MENU_LIST_START_GAP - MENU_SCROLL_TOP) // MENU_ROW_HEIGHT
MENU_SCROLL_HEIGHT = MENU_VISIBLE_ROWS * MENU_ROW_HEIGHT
MENU_SCROLL_LEFT = MENU_BUTTON_LEFT - MENU_LIST_SIDE_PADDING
MENU_SCROLL_WIDTH = MENU_BUTTON_WIDTH + 2 * MENU_LIST_SIDE_PADDING
MENU_CHECKBOX_LEFT = MENU_BUTTON_LEFT
MENU_CHECKBOX_TOP = MENU_SCROLL_TOP + (MENU_ROW_HEIGHT - MENU_CHECKBOX_SIZE) // 2

MENU_CREDITS_SIDE_MARGIN = 40
MENU_CREDITS_BOTTOM_MARGIN = 40
MENU_CREDITS_HEIGHT = 40
MENU_CREDITS_TOP = SCREEN_HEIGHT - MENU_CREDITS_BOTTOM_MARGIN - MENU_CREDITS_HEIGHT

MENU_BACK_LEFT = 40
MENU_BACK_WIDTH = 180

SETTINGS_WIDTH = 1040
SETTINGS_LEFT = (SCREEN_WIDTH - SETTINGS_WIDTH) // 2
SETTINGS_TITLE_TOP = 80
SETTINGS_FIRST_ROW_TOP = 160
SETTINGS_LABEL_GAP = 12
SETTINGS_ROW_GAP = 24
SETTINGS_OPTION_GAP = 16

HUD_BUTTON_WIDTH = 140
HUD_BUTTON_HEIGHT = 48
HUD_PANEL_GAP = 12
CONTINUE_HORIZONTAL_PADDING = 24

BUTTON_PRESS_DOWN_MS = 60
BUTTON_PRESS_HOLD_MS = 40
